### ISSUE TITLE
Rename to WorseXray

### ISSUE THREAD

**Issue by HyperEnte** [HimmelKreis4865/AntiXray#1]
Super Plugin, aber der Name ist etwas verwirrend

**Comment by HimmelKreis4865** [comment]
Welp, ich denke WorseXray macht die sache noch ein bisschen mehr verwirrender. Aber joa, ich mache mir mal ein paar Gedanken, vlt auch sowas wie AntiXray? 🤔

**Comment by HyperEnte** [comment]
Ja, oder sowas eindeutiges wie XRayBlocker

**Comment by HimmelKreis4865** [comment]
Ich werde soetwas einplanen & mir einen Namen überlegen in nächster Zeit

**Comment by inxomnyaa** [comment]
LeadShield wär doch was, da Blei vor der Strahlung schützt

**Comment by HimmelKreis4865** [comment]
Habe es jetzt ganz simpel AntiXray genannt, LeadShield klingt zwar cool aber sorgt wahrscheinlich für Verwirrung?
