### ISSUE TITLE
Items in Itemframes und Truhen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by EntenGamesNET** [HimmelKreis4865/AntiXray#2]
Hey :)
Solange das Plugin auf dem Server ist, werden für den Spieler die Items in den Itemframes und Truhen nicht angezeigt.
Erst nachdem man die Blöcke abbaut, droppen die Items in den Frames/Truhen.
Wäre cool, wenn du das fixen kannst, ansonsten super Plugin!

**Comment by HimmelKreis4865** [comment]
Hallo,

könnte ich bitte noch genauere Informationen zu dem Problem bei Truhen erhalten? Ich kann diesen Fehler nicht reproduzieren, das mit den Itemframes ist bei mir auch aufgetreten, ich werde versuchen es zu beheben ^^

**Comment by HimmelKreis4865** [comment]
So, mit dem letzten Commit sollten ItemFrames und andere tiles (wie unter anderem Truhen) nun automatisch zu dem Chunk hinzugefügt werden bevor er serialisiert wird. 
Bei mir funktioniert alles sehr gut, bitte einfach melden falls es weiterhin Komplikationen gibt!

**Comment by EntenGamesNET** [comment]
```
Error: Too many packets in a single batch
File: src/pocketmine/network/mcpe/protocol/BatchPacket
Line: 101
Type: UnexpectedValueException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: BetterXray v1.0.0

Code:

Backtrace:
#0 plugins/BetterXray/src/HimmelKreis4865/BetterXray/EventListener(28): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
#1 src/pocketmine/plugin/MethodEventExecutor(42): HimmelKreis4865\BetterXray\EventListener->chunkPacket(object pocketmine\event\server\DataPacketSendEvent)
#2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object HimmelKreis4865\BetterXray\EventListener, object pocketmine\event\server\DataPacketSendEvent)
#3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent)
#4 src/pocketmine/Player(3556): pocketmine\event\Event->call()
#5 src/pocketmine/Server(1874): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket, boolean , boolean )
#6 src/pocketmine/Server(1856): pocketmine\Server->broadcastPacketsCallback(object pocketmine\network\mcpe\protocol\BatchPacket, array[4], boolean )
#7 src/pocketmine/level/Level(999): pocketmine\Server->batchPackets(array[4], array[540], boolean , boolean )
#8 src/pocketmine/level/Level(837): pocketmine\level\Level->actuallyDoTick(integer 3007)
#9 src/pocketmine/Server(2373): pocketmine\level\Level->doTick(integer 3007)
#10 src/pocketmine/Server(2496): pocketmine\Server->checkTickUpdates(integer 3007, double 1614524242.1999)
#11 src/pocketmine/Server(2264): pocketmine\Server->tick()
#12 src/pocketmine/Server(2107): pocketmine\Server->tickProcessor()
#13 src/pocketmine/Server(1691): pocketmine\Server->start()
#14 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[29] /home/GameServer/CityBuild-1/, string[37] /home/GameServer/CityBuild-1/plugins/)
#15 src/pocketmine/PocketMine(304): pocketmine\server()
```
Ich hab diesen Crash noch bekommen, als viel Sand von oben runter gefallen ist. Vielen Dank für den anderen Fix :)

**Comment by HimmelKreis4865** [comment]
Hmm, dieser Fehler muss eigentlich ein indirekter Fehler von Pocketmine sein da dort wohl mehr als 500 Packets in eine batch gepackt wurden. Der Fehler hat allerdings nichts direkt mit BetterXray zutun und es wundert mich, dass pocketmine sowas zulässt

Ich kann höchstens versuchen ein workaround zu machen und dann anstatt `$batch->getPackets()` eine eigene Funktion ohne Limit zu nutzen, mal sehen was sich da machen lässt

**Comment by EntenGamesNET** [comment]
Ja, an sowas hab ich auch gedacht. Vielleicht sowas wie ne Queue oder so. Wäre cool, wenn du sowas machen könntest.

**Comment by HimmelKreis4865** [comment]
Joa, das Hauptproblem ist, dass man unendlich viele Pakete in ein Batchpacket packen kann, aber nur maximal 500 aus einem auslesen kann.

**Comment by HimmelKreis4865** [comment]
So, mit dem Commit sollte auch das gefixxt sein. Bitte um eine Rückmeldung ob es weiterhin Probleme verursacht / jetzt alles passt

**Comment by EntenGamesNET** [comment]
Ah sorry, wollte noch ein Kommentar da lassen. Ich hatte bisher keine Probleme mehr, danke dir :)
