### ISSUE TITLE
Fake Erze sieht man regelmäßig unter der Erde

### ISSUE THREAD

**Issue by Joshiiiii** [HimmelKreis4865/AntiXray#3]
![Screenshot_1740](https://user-images.githubusercontent.com/49375131/111894971-b4f48b80-8a0f-11eb-867b-fe41722e6cb2.png)
Man sieht fast alle Fake Blöcke auch leider ohne XRay. Kann man da vielleicht iwas machen, dass die, wenn man in der Nähe ist entfernt werden?

**Comment by HimmelKreis4865** [comment]
Auf welcher X / Z Koordinate befindet sich die gezeigte Wand mit den Ores?

**Comment by Joshiiiii** [comment]
Ich denke, das Problem ist eher die Y Koordinate. Würde so einschätzen, dass es ab 40 losgeht.
Allerdings hast du auch auf den Screenshots X/Z. Ist aber eine andere Stelle in einer anderen Welt.
![Screenshot_1747](https://user-images.githubusercontent.com/49375131/111913046-9ec8e880-8a6c-11eb-8e63-6f17a0377d58.png)
![Screenshot_1748](https://user-images.githubusercontent.com/49375131/111913048-9f617f00-8a6c-11eb-8362-af753ae5e368.png)

**Comment by HimmelKreis4865** [comment]
habe es jetzt mal versucht zu reproduzieren - aber komme auf bei weitem weniger Erze auf viel größerer Fläche. 
Auch ab Höhe 40 konnte ich nichts feststellen, aber ich weiß noch von einem früheren issue an einem anderen projekt wo ein ähnlicher Fehler aufgetreten ist.

Dachte es würde daran liegen, dass es an den chunk bodern nicht alles berechnen kann, daher wäre es cool du würdest nochmal die koordinaten von der wand in Bild 1 wo die ganzen Erze sind sagen (X / Z koordinate von dem redstoneblock z.B)
